name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ghostcomms
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s --health-timeout=5s --health-retries=20
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ghostcomms
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Server deps + prisma
        working-directory: server
        run: |
          npm ci
          npx prisma generate
          npx prisma db push
          npx tsc --noEmit
      - name: Client build
        working-directory: client-web
        run: |
          npm ci
          npm run build
