# .github/workflows/nightly.yml
name: Nightly Maintenance

on:
  schedule:
    - cron: "17 2 * * *" # daily at 02:17 UTC (change as you like)
  workflow_dispatch:

jobs:
  prune-expired:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Sanity (print versions & confirm env)
        run: |
          npx prisma -v
          node -e "console.log('DATABASE_URL present:', !!process.env.DATABASE_URL)"
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Delete expired envelopes
        run: |
          npx prisma db execute --file - <<'SQL'
          DELETE FROM "Envelope" WHERE "expiresAt" < NOW();
          SQL
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
